routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return view('welcome');
});

Route::resource('/events', 'HolidayController');
Route::get('/addevent', 'HolidayController@display');

Route::get('/displaydata', 'HolidayController@show');

Route::get('/deleteevent', 'HolidayController@show');

Route::resource('/daterange', 'DateRangeController');

app/Holiday.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Holiday extends Model
{
    protected $table = 'events';
    protected $fillable = ['title', 'color', 'start_date', 'end_date'];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DateRangeController.php
<?php

namespace App\Http\Controllers;

use DB;
use Illuminate\Http\Request;

class DateRangeController extends Controller
{
    public function index(Request $request)
    {
        if (request()->ajax()) {
            if (!empty($request->start_date)) {
                $data = DB::table('events')
                    ->whereBetween('start_date', array($request->start_date, $request->end_date))
                    ->get();
            } else {
                $data = DB::table('events')
                    ->get();
            }
            return datatables()->of($data)->make(true);
        }
        return view('daterange');
    }
}

app/Http/Controllers/HolidayController.php
<?php

namespace App\Http\Controllers;

use App\Holiday;
use Illuminate\Http\Request;
use MaddHatter\LaravelFullCalendar\Facades\Calendar;

class HolidayController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $events = Holiday::all();
        $event = [];

        foreach ($events as $row) {
            $enddate = $row->end_date . "00:00:00";
            $event[] = \Calendar::event(
                $row->title,
                true,
                new \DateTime($row->start_date),
                new \DateTime($row->end_date),
                $row->id,
                [
                    'color' => $row->color,
                ]

            );
        }

        $calendar = \Calendar::addEvents($event);
        return view('eventpage', compact('events', 'calendar'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */

    public function display()
    {
        return view('addevent');
    }
    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required',
            'color' => 'required',
            'start_date' => 'required',
            'end_date' => 'required',
        ]);

        $events = new Holiday;

        $events->title = $request->input('title');
        $events->color = $request->input('color');
        $events->start_date = $request->input('start_date');
        $events->end_date = $request->input('end_date');

        $events->save();

        return redirect('events')->with('success', 'Holiday Added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show()
    {
        $events = Holiday::all();
        return view('display')->with('events', $events);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $events = Holiday::find($id);
        return view('editform', compact('events', 'id'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'title' => 'required',
            'color' => 'required',
            'start_date' => 'required',
            'end_date' => 'required',
        ]);

        $events = Holiday::find($id);

        $events->title = $request->input('title');
        $events->color = $request->input('color');
        $events->start_date = $request->input('start_date');
        $events->end_date = $request->input('end_date');

        $events->save();

        return redirect('events')->with('success', 'Holiday info updated');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $events = Holiday::find($id);
        $events->delete();

        return redirect('events')->with('success', 'Holiday entry deleted');
    }
}

resources/views/addevent.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Add Event</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>
<body>
        <div class="container">
            <div class="jumbotron">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <div class="panel panel-default">
                            <div class="panel-heading" style="background: #2e6da4; color: white;">
                                Add Holiday to Calendar
                            </div>
        
                            <div class="panel-body">
                                <h2 align="center" ><strong> Insert holiday information</strong></h2>
                                <br>
                            <form method="post" action="{{action('HolidayController@store')}}" >
                            
                            {{ csrf_field() }}

                            <label for="">Enter the Name of the Holiday</label>
                            <input type="text" class="form-control" name="title" placeholder="Enter the Holiday" /><br /><br />

                            <label for="">Enter the color code</label>
                            <input type="color" class="form-control" name="color" placeholder="Enter the color" /><br /><br />

                            <label for="">Enter the start date of the holiday</label>
                            <input type="date" class="form-control" name="start_date" placeholder="Enter start date" /><br /><br />

                            <label for="">Enter the end date of the holiday</label>
                            <input type="date" class="form-control" name="end_date" placeholder="Enter end date" /><br /><br />

                            <input type="submit" name="submit" class="btn btn-primary" value="Add Event Data" />

                            <a href="/events" class="btn btn-danger">Back</a>

                            </form>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</body>
</html>

resources/views/daterange.blade.php
<html>
 <head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Daterange Filter</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
  <script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js"></script>  
  <link rel="stylesheet" href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css" />
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker.css" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.js"></script>
 </head>
 <body>
  <div class="container"> 
    <div class="col-md-10 col-md-offset-1">   
     <br />
     <div class="page-header">
        <h4><strong>Daterange Filter</strong></h4>
     </div>
            <br />

                <div class="row input-daterange">
                    <div class="col-md-4">
                        <input type="text" name="start_date" id="start_date" class="form-control" placeholder="From Date" readonly />
                    </div>
                    <div class="col-md-4">
                        <input type="text" name="end_date" id="end_date" class="form-control" placeholder="To Date" readonly />
                    </div>
                    <div class="col-md-4">
                        <button type="button" name="filter" id="filter" class="btn btn-primary">Filter</button>
                        <button type="button" name="refresh" id="refresh" class="btn btn-default">Refresh</button>
                    </div>
                </div>
                <br />
                <div class="table-responsive">
                    <table class="table table-bordered table-striped" id="holiday_table">
                        <thead>
                            <tr>
                                <th> Id </th>
                                <th> Title </th>
                                <th> Start Date </th>
                                <th> End Date </th>       
                            </tr>
                        </thead>
                    </table>
                </div>
                <a href="/events" class="btn btn-danger">Back</a>
    </div>
  </div>
 </body>
</html>

<script>
    $(document).ready(function(){
    $('.input-daterange').datepicker({
    todayBtn:'linked',
    format:'yyyy-mm-dd',
    autoclose:true
    });

    load_data();

    function load_data(start_date = '', end_date = '')
    {
    $('#holiday_table').DataTable({
    processing: true,
    serverSide: true,
    ajax: {
        url:'{{ route("daterange.index") }}',
        data:{start_date:start_date, end_date:end_date}
    },
    columns: [
        {
        data:'id',
        name:'id'
        },
        {
        data:'title',
        name:'title'
        },
        {
        data:'start_date',
        name:'start_date'
        },
        {
        data:'end_date',
        name:'end_date'
        },
    ]
    });
    }

    $('#filter').click(function(){
        var start_date = $('#start_date').val();
        var end_date = $('#end_date').val();
        if(start_date != '' &&  end_date != '')
        {
            $('#holiday_table').DataTable().destroy();
            load_data(start_date, end_date);
        }
        else
        {
            alert('Both Dates are required');
        }
    });

    $('#refresh').click(function(){
        $('#start_date').val('');
        $('#end_date').val('');
        $('#holiday_table').DataTable().destroy();
        load_data();
    });

    });
</script>

resources/views/display.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <title>All Events</title>

</head>
<body>

    <div class="container">
        <div class="jumbotron">

            <table class="table table-striped table-bordered table-hover">
                <thead class="thead">
                    <tr class="warning">
                        <th> Id </th>
                        <th> Title </th>
                        <th> Color </th>
                        <th> Start Date </th>
                        <th> End Date </th>
                        <th> Update </th>
                        <th> Delete </th>
                    </tr>
                </thead>
                @foreach($events as $event)
                <tbody>
                    <tr>
                        <td>{{ $event->id }}</td>
                        <td>{{ $event->title }}</td>
                        <td>{{ $event->color }}</td>
                        <td>{{ $event->start_date }}</td>
                        <td>{{ $event->end_date }}</td>

                    <th><a href="{{action('HolidayController@edit',$event['id'])}}" class="btn btn-success">
                            Edit</a>
                    </th>

                    <th>
                        <form method="POST" action="{{action('HolidayController@destroy',$event['id'])}}">
                            
                            {{ csrf_field() }}

                            <input type="hidden" name="_method" value="Delete"/>
                            <button type="submit" class="btn btn-danger"> Delete </button>

                        </form>
                    </th>


                    </tr>
                </tbody>     
                @endforeach
            </table>
            <a href="/events" class="btn btn-danger">Back</a>
        </div>
    </div>
    
</body>
</html>

resources/views/editform.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <title>Edit Holidays</title>
</head>
<body>
    <div class="container">
        <div class="jumbotron">
            <form action="{{action('HolidayController@update', $id)}}" method="POST">

                    {{ csrf_field() }}

                <div class="jumbotron">
                    <h2><strong> Update holiday info </strong></h2>
                    <hr>

                    <input type="hidden" name="_method" value="Update">

                <div class="form-group">
                    <label> Name of the holiday</label>
                    <input type="text" class="form-control" name="title" placeholder="Enter name" value="{{$events->title}}">
                </div>
                <div class="form-group">
                    <label> Event Color</label>
                    <input type="color" class="form-control" name="color" placeholder="select color" value="{{$events->color}}">
                </div>
                <div class="form-group">
                    <label> Start date of the holiday</label>
                    <input type="date" class="form-control" name="start_date" placeholder="Enter start date" value="{{$events->start_date}}">
                </div>
                <div class="form-group">
                    <label> End date of the holiday</label>
                    <input type="date" class="form-control" name="end_date" placeholder="Enter end date" value="{{$events->end_date}}">
                </div>

                {{ method_field('PUT') }}

                <button type="submit" name="submit" class="btn btn-success">Update data</button>

                <a href="/displaydata" class="btn btn-danger">Back</a>

                </div>
                </div>
            </form>
        </div>
    </div>
</body>
</html>

resources/views/eventpage.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"/>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />

    <title>Holiday Manager</title>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment.min.js"></script>
    
    <script src="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.2.7/fullcalendar.min.js"></script>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.2.7/fullcalendar.min.css"/>

    

    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
    
</head>
<body>
        <div class="container">
            <div class="page-header">
                <h4><strong> Holiday Management Module </strong></h4>
            </div>
                <div class="text-center">
                    <div class="row" >
                        <a href="/addevent" class="btn btn-success"> Add Holiday </a>
                        <a href="/displaydata" class="btn btn-primary"> Edit Holiday </a>
                        <a href="/deleteevent" class="btn btn-danger"> Delete Holiday </a>
                        <a href="/daterange" class="btn btn-info"> View Holidays </a>
                    </div>
                </div>
            
                <br>
        
        <div class="row">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-10 col-md-offset-2">
                                    @if(count($errors) > 0)
                                        <div class="alert alert-danger">
                                            <ul>
                                                @foreach($errors->all() as $error)
                                                    <li>{{$error}}</li>
                                                @endforeach
                                            </ul>
                                        </div>
                                    @endif
                                    
                                    @if(\Session::has('success'))
                                        <div class="alert alert-success alert-dismissible" role="alert" style="width: 79%;">
                                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span></button>
                                            <p>{{ \Session::get('success') }}</p>
                                        </div>
                                    @endif
                        </div>
                    </div>
                </div>
            
                    
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading" style="background: #2e6da4; color: white;">
                        Holiday Calendar
                    </div>

                    <div class="panel-body">
                        {!! $calendar->calendar() !!}
                        {!! $calendar->script() !!}
                    </div>
                </div>
            </div>
            
        </div>
    
    </div>

</body>
</html>